export const SONG_TYPES = {
    OPENING: "OPENING",
    CLOSING: "CLOSING",
    INTERMEDIATE: "INTERMEDIATE",
    SPECIAL: "SPECIAL",
    SACRAMENT: "SACRAMENT"
}

export const PRAYER_TYPES = {
    OPENING: "OPENING",
    CLOSING: "CLOSING"
}

export const AGENDA_ITEMS = {
    SONG: "SONG",
    SPEAKER: "SPEAKER",
    PRAYER: "PRAYER",
    TESTIMONY: "TESTIMONY",
    SACRAMENT: "SACRAMENT",
    PRESIDING: "PRESIDING",
    CONDUCTING: 'CONDUCTING',
    CHORISTER: 'CHORISTER',
    ORGANIST: 'ORGANIST'
}